---
driver:
  name: azurerm

driver_config:
  subscription_id: '294daf5a-51db-45ec-b96a-71f01cd6df54'
  location: 'East US'
  machine_size: 'Standard_D1'

transport:
  ssh_key: ~/.ssh/id_kitchen-azurerm

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[maas::default]
    attributes:
  - name: clustercontroller
    run_list:
      - recipe[maas::clustercontroller]
    attributes:
